### ISSUE TITLE
Package Supplier Error Understanding

### ISSUE THREAD

**Issue by sukh-gill** [chitchats/chitchats-api-doc#18]
I was executing the call to create a shippment for the purpose of getting the rates, below is the data I've passed but the error I get is package_supplier field is invalid. I'm not sure how to move forward from this. Is there something incorrect with the data below?

`[name] => Jane Doe
            [address_1] => 413 South Eighth Street
            [address_2] => 
            [city] => Springfield
            [province_code] => IL
            [postal_code] => 62701-1905
            [country_code] => US
            [phone] => 647-909-6050
            [package_contents] => merchandise
            [description] => Test Description
            [value] => 100.00
            [value_currency] => usd
            [order_id] => 1
            [order_store] => 
            [package_type] => medium_flat_rate_box_1
            [weight_unit] => oz
            [weight] => 10.3
            [postage_type] => unknown
            [ship_date] => today`

**Comment by gshaw** [comment]
@sukh-gill you need to double check all the enumerated values with values in API docs.  Some accounts might not have access to all package and postage types.  I'd suggest starting with something simple like `parcel` instead of the flat rate box and see if that works.
