### ISSUE TITLE
API Returns Non-Existent Postage Labels

### ISSUE THREAD

**Issue by teamcoltra** [chitchats/chitchats-api-doc#19]
If your shipment is usps_first the postage label still returns https://chitchats.com/labels/shipments/SHIPMENTID.png when the USPS First Class labels are stored and given directly from AWS on the website and return a 404 from https://chitchats.com/labels/shipments/SHIPMENTID.png 

It would be my preference that it's updated for first class mail to return the proper label, but otherwise my secondary request would be to not give any response for that.

**Comment by gshaw** [comment]
I'm going to close this issue as I believe the system is working as expected.  If you have a question about how postage labels please post in the newly [opened discussions](https://github.com/chitchats/chitchats-api-doc/discussions).
