### ISSUE TITLE
Create A Shipment - postage type - chit_chats_international_not_tracked, error: {message: "Unable to fetch postage rate"}

### ISSUE THREAD

**Issue by Braedencraig** [chitchats/chitchats-api-doc#22]
When I set the postage_type to "chit_chats_international_not_tracked" when trying to create a shipment, I get back the error 
"Unable to fetch postage rate". When I switch to "unknown" it works fine, but under the postage rates I am given, out of the 4 in the response, the chit_chats_international_not_tracked international standard rate is not listed. 

Is this to be expected?

**Comment by gshaw** [comment]
Yes, unfortunately that service has been discontinued.  I'll be updating the docs in January.
https://chitchats.com/blog/chit-chats-international-standard-discontinued
