### ISSUE TITLE
Unable to fetch postage rate - staging

### ISSUE THREAD

**Issue by phpandrew** [chitchats/chitchats-api-doc#31]
When posting to staging.chitchats.com to get postage rates for chit_chats_canada_tracked, an error is returned each time:
> Unable to fetch postage rate

**Comment by gshaw** [comment]
It's possible that Canada Post wasn't enabled on your account.  Canada Tracked rates are only enabled for clients that sign up as a business.  If you post your client ID I can make the switch.

The other problem might be that the address of your shipment isn't valid.  E.g., postal code that doesn't exist.

**Comment by phpandrew** [comment]
@gshaw My staging client id is: 640927

**Comment by gshaw** [comment]
@phpandrew yup, your account had Canada Post disabled.  I manually enabled it.  It should work now as expected.

**Comment by phpandrew** [comment]
Thanks @gshaw that works now.

Follow up, are we able to create labels for Canada Post shipments through the API?

**Comment by gshaw** [comment]
@phpandrew if you buy a Canada Tracked postage you'll either get a Chit Chats label which  will be re-labeled at Chit Chats with a Canada Post label OR if you account is approved your account will print a Canada Post label (to save us time from re-labeling) but in both cases the shipment must be received by Chit Chats.  Even if your account prints a Canada Post label it can't be inducted at Canada Post.

So the answer is a technical *maybe* for what I think you are asking it's a no.  If you want to buy Canada Post labels that can be dropped off at Canada Post branches you'll need to integrate directly with Canada Post or other provider like EasyPost.
