### ISSUE TITLE
Unable to get the Postage Rates

### ISSUE THREAD

**Issue by Medanaresh** [chitchats/chitchats-api-doc#43]
for getting postage we hit the create shipment API with postage type as unknown but we are getting empty rates object, and shipment is created. kindly check the below screenshot, help me if anything wrong from my side.

![c1](https://user-images.githubusercontent.com/14160818/112165644-f1450900-8c14-11eb-93f9-caabd446daf1.png)
![c2](https://user-images.githubusercontent.com/14160818/112165649-f30ecc80-8c14-11eb-82c9-39b4a3a92224.png)

**Comment by gshaw** [comment]
@Medanaresh  can you reply with the following info

Steps to recreate (this is what I need, even the shipment ID would help with investigating)
What you expected (E.g., rates returned with the created rates)
What you saw (E.g., shipment with no rates)

**Comment by Medanaresh** [comment]
Hi @gshaw  Thanks for the reply 
1.Shipment Id R2Q3W96T12
2. I am expecting rates for the package so that i will display in website so the user can select 
3. I Got the replay with empty rates object 
4.
![image](https://user-images.githubusercontent.com/14160818/112191611-3163b600-8c2c-11eb-9836-1cc12802d4bb.png)

**Comment by gshaw** [comment]
@Medanaresh the shipment you created has a Canadian recipient but it doesn't include the package information.  Canada shipments need weight and dimensions to get rates.

If you were to look in the Chit Chats GUI you would see that it's missing package info.  You'll need to create a new shipment with package info to get rates.

**Comment by Medanaresh** [comment]
@gshaw thanks for the response but i am passing the passing weight , sizes also,  please find the below Jsondata , it contains parameters we are sending.

{
  "name": "Naresh Meda",
  "address_1": "123 ANYWHERE ST.",
  "address_2": "dffds",
  "city": "Vancouver",
  "province_code": "BC",
  "postal_code": "V6K 1A1",
  "country_code": "CA",
  "phone": "800-555-1212",
  "package_contents": "merchandise",
  "description": "Clothing",
  "value": "20",
  "value_currency": "USD",
  "order_id": "",
  "order_store": "",
  "package_type": "parcel",
  "weight_unit": "g",
  "weight": "500",
  "size_unit": "cm",
  "size_x": "10",
  "size_y": "5",
  "size_z": "3",
  "postage_type": "unknown",
  "tracking_number": "",
  "ship_date": "today"
}

**Comment by gshaw** [comment]
Your staging account didn't have Canada Tracked postage enabled.  I've fixed the problem and things should work now.

**Comment by Braedencraig** [comment]
@gshaw I'm having a similar issue right now on staging! Could I trouble you to enable Canada Tracked postage for me as well? My client id is 421169! Do you need anymore info!? Thank you!

**Comment by jbuyco** [comment]
@Braedencraig Client ID is enough information thank you; I've enabled Canada Tracked postage for your client account.

**Comment by Braedencraig** [comment]
@jbuyco Thank you SO much!!

**Comment by Braedencraig** [comment]
@jbuyco Could I get the same done for Client ID 162008?! Thank you!!!!

**Comment by jbuyco** [comment]
@Braedencraig I've updated Canada Tracked postage for your other Client ID 162008.
