### ISSUE TITLE
Can't delete paid/status=ready orders from staging.chitchats dashboard.

### ISSUE THREAD

**Issue by Braedencraig** [chitchats/chitchats-api-doc#54]
I currently cannot delete paid/ready orders from my chitchats staging account. Am I missing something? I feel like this functionality worked previously, but maybe there is something I am not doing. When I select an order(s), I click the other dropdown, and Request Refund/Duplicate are actionable, but Delete is disabled/greyed out.

The orders are under pending in the dashboard, if that helps.

**Comment by jbuyco** [comment]
Hi Braeden, 

We have a policy such that the shipment must not be paid in order to delete. In this case you will have to request a refund first, wait for the refund to come through, then you can delete the shipment.

**Comment by Braedencraig** [comment]
Okay! thank you for that!

Are refund requests in staging processed quickly? or is there the same waiting period as on prod?

**Comment by jbuyco** [comment]
@Braedencraig It depends on the type of postage which was purchased, but in most cases it should be relatively quick.

**Comment by Braedencraig** [comment]
Amazing! Saw most of them just approved promptly! Thank you so much!
