### ISSUE TITLE
PNG Postage urls are protected by auth tokens

### ISSUE THREAD

**Issue by keiraarts** [chitchats/chitchats-api-doc#55]
From August 10th, new shipping labels we're purchasing through ChitChat's API have url references protected by auth tokens.

Previous the  **postage_label_zpl_url** had values similar to:
'https://chitchats.com/labels/shipments/s9c09a1b4a.png'

Today those values are protected with auth tokens:
'https://chitchats.com/labels/shipments/s9c09a1b4a.png?auth_token=BAhbCGkDOpkGbC'

We're printing labels using another app (not on ChitChats website) and these new tokens prevent us from downloading the label as images to later print on our thermal printers. It's a combination of getting "is not allowed by Access-Control-Allow-Origin" errors loading the postage labels and not being able to fetch it through a service like Cloudinary because of the new tokens.

Is there any way to remove auth query tokens from the API response?

**Comment by HansDaigle** [comment]
+1 for this. We have to stop all shipments through chitchat until this is resolved.

**Comment by gal3** [comment]
Are you able to access the label using the URL?

The host URL also changed from **assets.chitchats.com** to **chitchats.com**

I'm not familiar with Cloudinary, but is it related to this?
https://cloudinary.com/documentation/fetch_remote_images#creating_a_fetch_url_containing_special_characters

**Comment by HansDaigle** [comment]
Hey @gal3,

The URL did change, I used to have it hardcoded in my code but now you can get it with `shipment_data['shipment'].get('postage_label_png_url')`.

I used to do:

```
label_ext = cfg.get("chitchats", "label_ext").strip(".")  # png or pdf

label_url = f"https://assets.chitchats.com/labels/shipments/{shipment_data['shipment'].get('id').lower()}.{label_ext}" if cfg.getboolean("chitchats", "use_prod") else f"https://d2exzhpzkrnn4t.cloudfront.net/labels/shipments/{shipment_data['shipment'].get('id').lower()}.{label_ext}"
```

And how with the new URL, and auth_token I only do:
```
label_url = shipment_data['shipment'].get('postage_label_png_url')
```

On top of that, the `shipment_data['shipment'].get('postage_label_png_url')` seems to include an auth_token now (in prod only).

The `auth_token` is actually the same as your `remember_token` cookie and they are interchangeable, meaning that even if the second piece of the token (`X1X1X1X1X1X1X1X1X1X1X1X1X1X1X1--41e32d53aaebe7531f3df34c43c5f768aae7ae4e`) change it will still be valid to get any label. The first part doesn't change.

**Comment by rajbirverma** [comment]
Closing this as we assume @gal3's suggestion helped address the issue you were having. Please reopen if issue persists.
