### ISSUE TITLE
Add example for creating a shipment with existing postage

### ISSUE THREAD

**Issue by gshaw** [chitchats/chitchats-api-doc#6]
You can use the API to create a shipment that already has postage, e.g., BYO postage the same way you do this when importing with CSV.  Leaving the `ship_date` blank and optionally passing a `tracking_code` value.  If you pass a `tracking_code` value Chit Chats will track the shipment in your dashboard.

The docs should be updated to include an example request of doing this.

**Comment by lylesback2** [comment]
Thank you @gshaw this was helpful!
