### ISSUE TITLE
Update shipments when postage is not purchased yet

### ISSUE THREAD

**Issue by jeromegv** [chitchats/chitchats-api-doc#64]
Hi

I'd like the ability to update/edit shipments when the postage is not purchased yet. 
I don't see any way to do it through the API, is that something that could be added?

**Comment by mlywe** [comment]
Unfortunately, we don't support editing shipment through API.

I think you've reached out to our CS as well regarding editing HS Code from Shopify import? If so, you may try the new bulk edit shipment item feature that was just enabled yesterday:
- start Shopify import
- click [`Line Item View`](https://github.com/chitchats/chitchats-api-doc/assets/3010389/e6734e14-54be-4d0e-af75-67e2cc639fff) on bottom right corner of /clients/_/import/select
- select the line item row(s) to edit
  - note that only International and U.S. Territory / Military addresses will have line items on the platform as of this writing
- click `Edit # Line Item(s)`

**Comment by jeromegv** [comment]
Our fulfilment staff doesn't have capacity/ability to manually go through editing international shipments every day they import shipments. That's why we either need to have the Shopify integration imports those HS code that are stored in Shopify, or have an API-based solution. 

Do you realize how much time we need to spend every day having to manually import and edit shipments? We have a variety of sku and products and HS codes so the bulk edit shipments isn't really helping as we still need to do it manually for every single product. We don't just sell a single product that has the same HS code across all orders.

A single SKU product always have the same HS code, forever, which should make it easy to automate. We really need a solution to address that, either through the API or through the Shopify integration. I hope you can consider that in your roadmap

Thank you!

**Comment by mlywe** [comment]
Thank you for the feedback. I understand your frustration and this whole line item editing is new to us and we are fleshing out what works best for most Clients workflow. 

> A single SKU product always have the same HS code

Preset for bulk edit shipment item is coming up. It might be up when the office re-opens next year but this would not completely address your situation. Importing HS Code from store integration is in the roadmap especially for Shopify and ShipStation. They will happen early next year hopefully.

**Comment by jeromegv** [comment]
Sounds good, thank you for your response!

**Comment by mlywe** [comment]
> That's why we either need to have the Shopify integration imports those HS code that are stored in Shopify

We just deployed a change that imports HS Code from Shopify orders. It requires you to disconnect and re-connect existing Shopify stores as we need to request more access from Shopify. 

Please give it a try to see if it helps your situation @jeromegv.

**Comment by jeromegv** [comment]
@mlywe this worked! it imported.
 And Chitchat is happy with the Shopify HS code format, which is 6 digits?

**Comment by mlywe** [comment]
That's great to hear!

Yes, below is the accepted HS Code format on ChitChats:
- Must contain exactly 6, 8, 10 or 12 digits e.g. 12345678, 1234.56
- May contain only digits and decimal points e.g. 1234.56

Feel free to close this issue if your issue is resolved.

**Comment by jeromegv** [comment]
Looks great, thank you so much
