### ISSUE TITLE
Can you setup a php example for using this api

### ISSUE THREAD

**Issue by sahermannan** [chitchats/chitchats-api-doc#9]

**Comment by getfaxing** [comment]
I created a plug-in for WooCommerce (a Wordpress plugin) written in php.  It generates a pending shipment in Chit Chats automatically when an order is received & paid for.  It is working how I like it but really have to clean up the code (lots of trial and error stuff there, and I'm not an WooCommerce/Php expert).  I'll try to post a snippet of the API related code that might help you.

**Comment by sahermannan** [comment]
Thanks, 

Anxiously waiting for your response 

-- 

HAVE A NICE DAY! 
_SAHER MANNAN_ 

On 2018-11-12 11:42, getfaxing wrote:

> I created a plug-in for WooCommerce (a Wordpress plugin) written in php. It generates a pending shipment in Chit Chats automatically when an order is received & paid for. It is working how I like it but really have to clean up the code (lots of trial and error stuff there, and I'm not an WooCommerce/Php expert). I'll try to post a snippet of the API related code that might help you. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/chitchats/chitchats-api-doc/issues/9#issuecomment-437949043
[2]

**Comment by gshaw** [comment]
It's unlikely we will provide a PHP example.  The API is a standard REST API should it should be able to be consumed in any language.  If somebody provides a PHP example we could link out to that.
